### ISSUE TITLE
make the base path for the admin ui configurable

### ISSUE THREAD

**Issue by brharrington** [Netflix/karyon#127]
It seems like the path used for karyon differs from the path used internally with the platform stack. Example for jars, but jars could be replaced with any admin endpoint:

* karyon: `/admin#view=jars` and `/webadmin/jars`
* baseserver: `/baseserver#view=jars` and `/v1/platform/base/jars`

Can this be made configurable? Internally that would ease adoption as tooling wouldn't need to worry about which path was used for a given service.

**Comment by NiteshKant** [comment]
@amit-git I believe this is fixed in 2.2.00-ALPHA7?

**Comment by amit-git** [comment]
Yes

Sent from my iPhone

On Jan 24, 2015, at 12:08 AM, Nitesh Kant <notifications@github.com> wrote:

@amit-git <https://github.com/amit-git> I believe this is fixed in
2.2.00-ALPHA7?

—
Reply to this email directly or view it on GitHub
<https://github.com/Netflix/karyon/issues/127#issuecomment-71304690>.

**Comment by brharrington** [comment]
I confirmed that by switching to 2.2.00-ALPHA7 and setting the properties below I get the expected paths. Thanks.

```
netflix.admin.template.context=/baseserver
netflix.admin.resource.context=/v1/platform/base
```
