### ISSUE TITLE
Leaking IO Scheduler Threads, Jersey Blocking

### ISSUE THREAD

**Issue by maksimlikharev** [Netflix/karyon#200]
In JerseyBasedRouter there is following code:

```
        return Observable.create(new Observable.OnSubscribe<Void>() {
            @Override
            public void call(Subscriber<? super Void> subscriber) {
                try {
                    application.handleRequest(containerRequest, containerResponse);
                    subscriber.onCompleted();
                } catch (IOException e) {
                    logger.error("Failed to handle request.", e);
                    subscriber.onError(e);
                }
```
 __In here subscriber still subscribed, so Scheduler thread not returned to the pool__
Leaking thread probably not in a grand design, but at the same time __onCompleted/onError__ called.
I'm not really sure what is going on and where the problem is, but if I do this:
```
                finally {
                  subscriber.unsubscribe();
                }
```
all seems to be getting back to normal. Could you please look if there is a substance in this unsubscribe call or maybe that's just an ugly hack and the real problem lies somewhere else.
```
            }
        }).doOnTerminate(new Action0() {
            @Override
            public void call() {
                response.close(true); /* Since this runs in a different thread, it needs an explicit flush,
                                         else the LastHttpContent will never be flushed and the client will not finish.*/
            }
        }).subscribeOn(Schedulers.io()) /*Since this blocks on subscription*/;
```

**Comment by NiteshKant** [comment]
@maksimlikharev looks like it is the same issue as mentioned in this issue #122 

I think the problem is with `InterceptorExecutor`[here](https://github.com/Netflix/karyon/blob/master/karyon2-core/src/main/java/netflix/karyon/transport/interceptor/InterceptorExecutor.java#L70) which is not adding the `ChainSubscriber` to the `SerialSubscription` and the `SerialSubscription` to the child.

The issue comes up with the `JerseyBasedRouter` as it uses a new threads which leaks but the basic issue is that the `unsubscribe` is swallowed by the `InterceptorExecutor` if there are no interceptors.

I will send a PR soon for this.
